#%RAML 1.0
title: openlogix-base64-sapi
description: Utility api enabling to encode to Base64 string or decode from Base64 to actual file
protocols: [https]
version: v1
baseUri: /api/{version}/

types:
  EncodeFile:
    type: file
    fileTypes: ["image/jpeg", "image/jpg", "image/png", "text/plain", "application/pdf"]

  DecoderInput:
    properties:
      outputFileName:
        type: string
        example: "file.png"
      fileContent:
        type: string
        example: "Base64String...."

/encode:
  post:
    body:
      multipart/form-data:
        properties:
          file: 
            type: EncodeFile

/decode:
  post:
    body:
      application/json:
        type: DecoderInput
    